version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    assignees:
      - "orlangure"
  - package-ecosystem: "gomod"
    directory: "/cmd/cleaner"
    schedule:
      interval: "daily"
      time: "09:00"
